export interface Patient {
  id: number,
  name: string,
  surname: string,
  birthDate: Date,
  pesel: string,
  sex: string,
  address: string,
  city: string,
  email: string,
  phone: string,
  lifestyle: string,
  profession: string,
  guardian: string,
  pastDiseases: string,
  chronicDiseases: string,
  hospitalization: string,
  surgeries: string,
  pastTreatment: string,
  allergies: string,
  familyDiseases: string,
  medicalCertificate: string,
  extraDetails: string,
}
